local options = {
	backup = false,
	clipboard = "unnamedplus",
	cmdheight = 0,
	copyindent = true,
	expandtab = true,
	fileencoding = "utf-8",
	relativenumber = false,
	history = 100,
	ignorecase = true,
	laststatus = 3,
	number = true,
	showtabline = 2,
	mouse = "a",
	preserveindent = true,
	swapfile = false,
	tabstop = 2,
	shiftwidth = 2,
	termguicolors = true,
	timeoutlen = 300,
	undofile = true,
	updatetime = 300,
	wrap = false,
	lazyredraw = true,
	fillchars = { eob = " " },
	pumheight = 10,
	scrolloff = 8,
	smartcase = true,
	splitbelow = true,
	splitright = true,
	writebackup = false,
	signcolumn = "auto:2",
}

for k, v in pairs(options) do
	vim.opt[k] = v
end
